### ISSUE TITLE
Ethash.prototype.calcDatasetItem not work

### ISSUE THREAD

**Issue by perl5577** [ethereum/ethashjs#1]
For debuging
  console.log('Ethash.prototype.calcDatasetItem 1');
  console.log(mix);
  console.log('i:' + i +  ' n:' + n + ' r:' + r);
  mix.writeInt32LE(mix.readUInt32LE(0) ^ i)

Ethash.prototype.calcDatasetItem 1
<Buffer 62 8e 0a 0d e9 eb 22 c1 0a b0 d7 b3 29 e0 ae f4 f0 b9 f2 5e ef da c5 9d b8 e3 a7 ee 7c 08 66 8a f8 c2 1c 1e b0 13 34 61 4f b9 5a 43 27 24 6d af 1c 86 5c ...>
i:12511692 n:264179 r:16

buffer.js:786
    throw TypeError('offset is not uint');
          ^

**Comment by wanderer** [comment]
Your are not really suppose to use that `calcDatasetItem` directly. I wrote you an [example](https://github.com/ethereum/ethashjs/blob/master/example/example.js) let me know how it goes!

**Comment by perl5577** [comment]
Nop

I have add on index.js 

Ethash.prototype.verifySubmit = function(number,headerHash,nonce, cb) {
        var self = this
        console.log(number);
        this.loadEpoc(number, function(){
                console.log("EPOC set");
                console.log(this.seed);
                var a = self.run(headerHash, new Buffer(nonce, 'hex'), self.fullSize);
                var result = new BN(a.result);
                cb(result);
        })
}


const Ethash = require('ethashjs')
const levelup = require('levelup')
const memdown = require('memdown')

var cacheDB = levelup('', {
  db: memdown
})

var ethash = new Ethash(cacheDB);


var header = Buffer('0e2887aa1a0668bf8254d1a6ae518927de99e3e5d7f30fd1f16096e2608fe05e','hex') ;

ethash.verifySubmit(35414,header, 'e360b6170c229d15',function (result) {
 consol.log(result);
});

**Comment by perl5577** [comment]
run -> verifySubmit -> loadEpoc - > getEpoc  // this.epoc is set
                                                    -> findLastSeed  // I have make many coorection for working ( not work if epoc >= 1 )
                                                                   -> cacheDB.get  //Fixing seed utils
                                                                                  ->mkcache  // Failed

**Comment by wanderer** [comment]
ok @perl5577 can you run this https://gist.github.com/wanderer/7520ae8cd84397c6dc91 with the lastest code. And see if that works?
